const controlMappingEnLabels = <String, String>{
  'Click': 'Single press',
  'Double Click': 'Double press',
  'Triple Click': 'Triple press',
  '3-Pos Switch': '3 POS',
  '3-Pos': '3 POS',
  '2-Pos': '2 POS',
  '4WS Mode Switch': '4WS Mixing Mode',
  '4WS Front': '4WS Mixing Front',
  '4WS Rear': '4WS Mixing Rear',
  '4WS F/R Same': '4WS Mixing Same',
  '4WS F/R Reverse': '4WS Mixing Rev.',
  'Drive Mix Toggle': 'Drive Mix Mode',
  'Drive Mix Front': 'Drive Mix F Drive',
  'Drive Mix Rear': 'Drive Mix R Drive',
  'Drive Mix F/R Hybrid': 'Drive Mix F-R Drive',
  'Steering Ratio': 'Steering Rate',
  'Forward Ratio': 'F Rate',
  'Brake Ratio': 'B Rate',
  '4WS Mix Ratio': '4WS Mix Rate',
  'Drive Mix Forward Ratio': 'Drive Mix F Rate',
  'Drive Mix Reverse Ratio': 'Drive Mix R Rate',
  'Brake Mix Ratio': 'Brake Mix Rate',
};
