import 'types.dart';

const initialChannels = <ChannelState>[
  ChannelState(
    id: 'CH1',
    name: 'Aileron',
    value: 42,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 95,
    dualRate: 100,
    failsafeActive: true,
    failsafeValue: 0,
  ),
  ChannelState(
    id: 'CH2',
    name: 'Elevator',
    value: -18,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 95,
    dualRate: 85,
    failsafeActive: false,
    failsafeValue: 95,
  ),
  ChannelState(
    id: 'CH3',
    name: 'Throttle',
    value: 100,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 0,
    dualRate: 100,
    failsafeActive: false,
    failsafeValue: 100,
  ),
  ChannelState(
    id: 'CH4',
    name: 'Rudder',
    value: 0,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 12,
    dualRate: 70,
    failsafeActive: true,
    failsafeValue: 0,
  ),
  ChannelState(
    id: 'CH5',
    name: 'AUX 1',
    value: 20,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 0,
    dualRate: 100,
    failsafeActive: false,
    failsafeValue: 20,
  ),
  ChannelState(
    id: 'CH6',
    name: 'AUX 2',
    value: 85,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 0,
    dualRate: 100,
    failsafeActive: false,
    failsafeValue: 85,
  ),
  ChannelState(
    id: 'CH7',
    name: 'FLAP',
    value: 0,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 15,
    dualRate: 100,
    failsafeActive: true,
    failsafeValue: 0,
  ),
  ChannelState(
    id: 'CH8',
    name: 'AUX 3',
    value: 35,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 0,
    dualRate: 100,
    failsafeActive: false,
    failsafeValue: 35,
  ),
  ChannelState(
    id: 'CH9',
    name: 'AUX 4',
    value: 0,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 0,
    dualRate: 100,
    failsafeActive: false,
    failsafeValue: 0,
  ),
  ChannelState(
    id: 'CH10',
    name: 'AUX 5',
    value: -20,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 8,
    dualRate: 100,
    failsafeActive: true,
    failsafeValue: -20,
  ),
  ChannelState(
    id: 'CH11',
    name: 'AUX 6',
    value: 60,
    lLimit: 100,
    rLimit: 100,
    reverse: false,
    offset: 0,
    dualRate: 100,
    failsafeActive: false,
    failsafeValue: 60,
  ),
];

const initialModels = <Model>[
  Model(id: 'MOD01', name: 'MOD01', active: true),
  Model(id: 'MOD02', name: 'MOD02', active: false),
  Model(id: 'MOD03', name: 'MOD03', active: false),
  Model(id: 'MOD04', name: 'MOD04', active: false),
  Model(id: 'MOD05', name: 'MOD05', active: false),
  Model(id: 'MOD06', name: 'MOD06', active: false),
  Model(id: 'MOD07', name: 'MOD07', active: false),
  Model(id: 'MOD08', name: 'MOD08', active: false),
];

const initialRadioSettings = RadioSettings(
  backlightTime: 50,
  idleAlarm: 600,
  atmosphereLight: true,
);

const initialTelemetry = Telemetry(
  txVoltage: -1,
  rxVoltage: -1,
  signalStrength: 0,
  latency: 1.2,
);

const initialMixingSettings = MixingSettings(
  activeMode: '4WS',
  enabled: true,
  ratio: 95,
  curve: 0,
  direction: '4WS_REAR_SAME',
  selectedChannel: 'CH3',
);

const initialBluetoothSettings = BluetoothSettings(
  devices: [
    BluetoothDevice(
      id: 1,
      name: '蓝牙 1',
      mac: '4C:65:A8:12:90:BC',
      connected: true,
      type: 'phone',
      signal: 3,
    ),
    BluetoothDevice(
      id: 2,
      name: '蓝牙 2',
      mac: '2A:F3:11:00:5E:D1',
      connected: false,
      type: 'audio',
      signal: 2,
    ),
    BluetoothDevice(
      id: 3,
      name: 'TITAN_BAND_X',
      mac: '00:1B:44:11:3A:B7',
      connected: false,
      type: 'watch',
      signal: 1,
    ),
  ],
  isScanning: false,
);
